"""Inin

Revision ID: 2daed8e645e1
Revises: b2c0d7f77804
Create Date: 2021-06-20 22:36:28.060792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2daed8e645e1'
down_revision = 'b2c0d7f77804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_secure', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
