"""two

Revision ID: b2c0d7f77804
Revises: f462ee21c5d0
Create Date: 2021-06-20 22:06:07.942716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c0d7f77804'
down_revision = 'f462ee21c5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_secure', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_secure')
    # ### end Alembic commands ###
